// Tiny character-trigram language detector for embedded use (Meshcore).
//
// Detects Polish / Slovak / German with a conservative decision rule and
// falls back to English (the public channel) whenever it is not sure.
//
//   * header-only, no heap, no floating point, no STL
//   * flash: ~16 KB of const tables (see lang_model.h), RAM: a few bytes
//   * cost: one binary search per character of input
//
// Usage:
//   #include "lang_detect.h"
//   LangChannel ch = ld_detect(text, strlen(text));   // LANG_EN if unsure
//
// The model tables and thresholds live in lang_model.h, generated by train.py.
#pragma once
#include <stddef.h>
#include <stdint.h>

#include "lang_model.h"

enum LangChannel { LANG_EN = 0, LANG_PL = 1, LANG_SK = 2, LANG_DE = 3 };

// Optional diagnostics filled in by ld_detect().
struct LangScores {
    uint32_t cost[LD_NLANG];   // summed -log2 P(text | lang) * 8, lower = more likely
    uint16_t ntrigrams;        // how many trigrams were scored (evidence amount)
    uint8_t best;              // model class with the lowest cost
};

// Decode one UTF-8 code point. Invalid bytes decode as 0 and consume 1 byte.
static inline size_t ld_utf8_decode(const uint8_t* s, size_t n, uint32_t* cp) {
    uint8_t c = s[0];
    if (c < 0x80) { *cp = c; return 1; }
    size_t len;
    uint32_t v;
    if ((c & 0xE0) == 0xC0)      { len = 2; v = c & 0x1F; }
    else if ((c & 0xF0) == 0xE0) { len = 3; v = c & 0x0F; }
    else if ((c & 0xF8) == 0xF0) { len = 4; v = c & 0x07; }
    else { *cp = 0; return 1; }
    if (len > n) { *cp = 0; return 1; }
    for (size_t i = 1; i < len; i++) {
        if ((s[i] & 0xC0) != 0x80) { *cp = 0; return 1; }
        v = (v << 6) | (s[i] & 0x3F);
    }
    *cp = v;
    return len;
}

// Map a code point to a model symbol: 0 = space/other, 1..26 = a..z,
// 27.. = the diacritic letters that distinguish PL/SK/DE. Other accented
// Latin letters fold to their base letter (via LD_CHARMAP), everything else
// (digits, punctuation, emoji, Cyrillic, ...) becomes a space.
static inline uint8_t ld_symbol(uint32_t cp) {
    if (cp >= 'A' && cp <= 'Z') cp += 'a' - 'A';
    if (cp >= 'a' && cp <= 'z') return (uint8_t)(cp - 'a' + 1);
    if (cp >= 0xC0 && cp < 0xC0 + sizeof(LD_CHARMAP)) return LD_CHARMAP[cp - 0xC0];
    return 0;
}

// Binary search in the sorted key table; returns index or -1.
static inline int ld_lookup(uint32_t key) {
    int lo = 0, hi = LD_NKEYS - 1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        uint32_t k = LD_KEYS[mid];
        if (k == key) return mid;
        if (k < key) lo = mid + 1; else hi = mid - 1;
    }
    return -1;
}

// Score a UTF-8 string: accumulate per-language trigram costs.
static inline void ld_score(const char* text, size_t len, LangScores* out) {
    for (int l = 0; l < LD_NLANG; l++) out->cost[l] = 0;
    out->ntrigrams = 0;
    out->best = 0;

    // Sliding window of the last three symbols. The text is treated as if it
    // were surrounded by single spaces and runs of spaces are collapsed.
    uint8_t w0 = 0, w1 = 0, w2 = 0;   // w2 = most recent symbol (starts as the leading space)
    uint16_t count = 1;               // symbols seen so far, including the leading space
    const uint8_t* s = (const uint8_t*)text;
    size_t i = 0;
    for (;;) {
        uint8_t sym = 0;               // 0 = the trailing space once input is exhausted
        bool at_end = (i >= len);
        if (!at_end) {
            uint32_t cp;
            i += ld_utf8_decode(s + i, len - i, &cp);
            sym = ld_symbol(cp);
        }
        if (sym != 0 || w2 != 0) {     // collapse repeated spaces
            w0 = w1; w1 = w2; w2 = sym;
            if (++count >= 3) {
                out->ntrigrams++;
                int idx = ld_lookup(((uint32_t)w0 << 12) | ((uint32_t)w1 << 6) | w2);
                if (idx >= 0)
                    for (int l = 0; l < LD_NLANG; l++) out->cost[l] += LD_COSTS[idx][l];
            }
        }
        if (at_end) break;
    }
    for (int l = 1; l < LD_NLANG; l++)
        if (out->cost[l] < out->cost[out->best]) out->best = (uint8_t)l;
}

// Decide the channel from scores. Returns LANG_EN unless the best language
//   * is a routed one (not English / not a public-channel class),
//   * has enough evidence (LD_MIN_TRIGRAMS),
//   * beats every public-channel class by LD_THRESH_VS_EN in total and by
//     LD_MIN_MARGIN_PER_TRIGRAM on average per trigram (so the *whole*
//     message leans that way, not just one word), and
//   * beats every other class by LD_THRESH_VS_OTHER.
// Costs are in units of bits * 8, so a threshold of 96 means the text is
// 2^12 = 4096 times more likely under the winning language.
static inline LangChannel ld_decide(const LangScores* sc) {
    if (sc->ntrigrams < LD_MIN_TRIGRAMS) return LANG_EN;
    int best = sc->best;
    if (LD_ROUTE[best] == 0) return LANG_EN;
    uint32_t bc = sc->cost[best];
    uint32_t need_vs_public = (uint32_t)sc->ntrigrams * LD_MIN_MARGIN_PER_TRIGRAM;
    if (need_vs_public < LD_THRESH_VS_EN) need_vs_public = LD_THRESH_VS_EN;
    for (int l = 0; l < LD_NLANG; l++) {
        if (l == best) continue;
        uint32_t margin = sc->cost[l] - bc;
        if (LD_ROUTE[l] == 0 && margin < need_vs_public) return LANG_EN;
        if (margin < LD_THRESH_VS_OTHER) return LANG_EN;
    }
    return (LangChannel)LD_ROUTE[best];
}

// The one-call API. `scores` may be NULL.
static inline LangChannel ld_detect(const char* text, size_t len, LangScores* scores = 0) {
    LangScores tmp;
    LangScores* sc = scores ? scores : &tmp;
    ld_score(text, len, sc);
    return ld_decide(sc);
}

static inline const char* ld_channel_name(LangChannel c) {
    switch (c) {
        case LANG_PL: return "PL";
        case LANG_SK: return "SK";
        case LANG_DE: return "DE";
        default: return "EN";
    }
}
